insert into "user" (username, password, nickname, activated) values ('admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 1);
insert into "user" (username, password, nickname, activated) values ('user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 1);

insert into authority (authority_name) values ('ROLE_USER');
insert into authority (authority_name) values ('ROLE_ADMIN');

insert into user_authority (user_id, authority_name) values (1, 'ROLE_USER');
insert into user_authority (user_id, authority_name) values (1, 'ROLE_ADMIN');
insert into user_authority (user_id, authority_name) values (2, 'ROLE_USER');



-- drop table if exists authority cascade;
-- drop table if exists "user" cascade;
-- drop table if exists user_authority cascade;
-- create table authority (
--                            authority_name varchar(50) not null,
--                            primary key (authority_name)
-- );
-- create table "user" (
--                         activated boolean,
--                         user_id bigint generated by default as identity,
--                         nickname varchar(50),
--                         username varchar(50) unique,
--                         password varchar(100),
--                         primary key (user_id)
-- );
-- create table user_authority (
--                                 user_id bigint not null,
--                                 authority_name varchar(50) not null,
--                                 primary key (user_id, authority_name)
-- );
-- alter table if exists user_authority
--     add constraint FK6ktglpl5mjosa283rvken2py5
--         foreign key (authority_name)
--             references authority;
-- alter table if exists user_authority
--     add constraint FKscuh0v3acg0xp6skwcvuynl6x
--         foreign key (user_id)
--             references "user";